server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://USER-SERVICE
          predicates:
            - Path=/book/**
        - id: jwtservice
          uri: lb://JWT-SERVICE
          predicates:
            - Path=/auth/login

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
