spring:
  application:
    name: PRODUCT-SERVICE
server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://54.253.150.0:8761/eureka
