version: '3.8'

services:
  urlshortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlshortener_app
    ports:
      - "8081:8080"  # Avoid port clash with other services
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/shortener
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
